### ISSUE TITLE
java.lang.NoClassDefFoundError: groovy/lang/GroovyObject

### ISSUE THREAD

**Issue by vikramvi** [basdijkstra/workshops#1]
pom.xml needs to be updated

<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-all</artifactId>
    <version>2.4.5</version>
</dependency>

http://stackoverflow.com/questions/25793068/java-lang-noclassdeffounderror-groovy-lang-groovyobject/25793187

Thanks,
Vikram

**Comment by basdijkstra** [comment]
Hey Vikram,

thanks for reporting that, I'll try and fix it later today.

-- Bas

Vikram Ingleshwar schreef op 2016-08-10 12:50:

**Comment by vikramvi** [comment]
Thanks

**Comment by basdijkstra** [comment]
Should be fixed now, please let me know if this works for you.

**Comment by vikramvi** [comment]
Thanks closing as fixed
