### ISSUE TITLE
transform proprietary PPTX into OpenDocument equivalent ODP

### ISSUE THREAD

**Issue by grexe** [basdijkstra/workshops#2]
It would be nice if an open source workshop also used free and open file formats (not wanting to dive into FSF-dogmas, but honestly I think this would be cool:)

See:
http://www.file-extensions.org/odp-file-extension

Don't know about PowerPoint->ODP export, but Word and Excel transparently handle ODF formats now, for saving and loading, so export should be straightforward.

**Comment by basdijkstra** [comment]
Hi Gregor,

You're absolutely 100% right on that. I'll fix that somewhere in the next couple of days. Thanks for the remark and for checking out the workshop.

Kind regards,

-- Bas

**Comment by basdijkstra** [comment]
Added ODP version of the presentation, removed .pptx.

**Comment by grexe** [comment]
thanks for adding the ODP version, if you assigned it to me for testing, I'm fine with it, feel free to close.
Now if I may only add one last minor complaint about the visual design... the Matrix style colors are a bit hard on my eyes, I'd prefer a more subtle design so I can concentrate better on the contents...

**Comment by basdijkstra** [comment]
Hey @grexe, thanks. The colors aren't going to change, I'm afraid. They've become a (small) part of my personal brand already.. Rest assured (pun fully intended) that it looks better on screen using a beamer..
